routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index')->with('title', 'Marshall Ashdowne | Full Stack Developer');
});

Route::resource('/contact', 'ContactFormsController', ['except' => [ 'edit', 'update', 'create' ]]);

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/ContactForms.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class ContactForms extends Model
{
  protected $table = "contact_forms";
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/ContactFormsController.php
<?php

namespace App\Http\Controllers;

use App\ContactForms;
use Illuminate\Support\Facades\Auth;
use Illuminate\Http\Request;

class ContactFormsController extends Controller
{
    public function index()
    {
        return view("contact")->with('title', 'Marshall Ashdowne | Contact');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      $form = new ContactForms();
      $form->title = $request->input('title');
      $form->content = $request->input('content');
      $form->contact = $request->input('contact');
      $form->save();

      return view("contacted")->with('title', 'Marshall Ashdowne | Contact');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\ContactForms  $contactForms
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
      if (!Auth::check()) {
        return redirect("/");
      }
      $form = \App\ContactForms::findOrFail($id);

      return view("view-contact")->with('form', $form)->with('title', 'Marshall Ashdowne | Contacts');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\ContactForms  $contactForms
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
      if (!Auth::check()) {
        return redirect("/");
      }
      \App\ContactForms::destroy($id);
      return redirect("/home");
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

resources/views/contact.blade.php
@extends("inc.app", ['contactMessage' => false])

@section("content")
  <div class="title">
    <div class="container top-nav">
      <div class="row">
        <div class="col-12">
          <div class="logo" onclick="document.location = '/';"><object class="" data="{{ asset('/storage/images/Logo.svg') }}" type="image/svg+xml"></object></div>
          <a class="btn right" href="/contact">Contact Me</a>
        </div>
      </div>
      <br>
      <form class="form" action="{{ action('ContactFormsController@store') }}" method="post">
        {{ csrf_field() }}
        <h1 class="white">Contact</h1>
        <div class="divider"></div>
        <br>
        <label for="title">Title</label>
        <input type="text" class="form-control" id="title" placeholder="I have this great idea..." name="title">
        <br>
        <label for="content">Content</label>
        <textarea rows="10" name="content"></textarea>
        <br>
        <br>
        <label for="contact">Contact Email</label>
        <input type="email" class="form-control" id="contact" name="contact">
        <br>
        <input type="submit" class="btn form-control" value="Send it off">
      </form>
    </div>
  </div>
  <script>
  //Only use screen size device begins with (since mobile browsers change screen size when scrolling down)
  $(".content")[0].style.top = ($(window).height() + 20) + "px";
  </script>
@endsection


@section("head")
  <script type="text/javascript" src="{{ asset('js/index.js') }}"></script>
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:700" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Quicksand" rel="stylesheet">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/brands.css" integrity="sha384-1KLgFVb/gHrlDGLFPgMbeedi6tQBLcWvyNUN+YKXbD7ZFbjX6BLpMDf0PJ32XJfX" crossorigin="anonymous">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/fontawesome.css" integrity="sha384-jLuaxTTBR42U2qJ/pm4JRouHkEDHkVqH0T1nyQXn1mZ7Snycpf6Rl25VBNthU4z0" crossorigin="anonymous">
@endsection

resources/views/contacted.blade.php
@extends("inc.app", ['contactMessage' => false])

@section("content")
  <div class="title">
    <div class="container top-nav">
      <div class="row">
        <div class="col-12">
          <div class="logo" onclick="document.location = '/';"><object class="" data="{{ asset('/storage/images/Logo.svg') }}" type="image/svg+xml"></object></div>
          <a class="btn right" href="/contact">Contact Me</a>
        </div>
      </div>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <h1 class="center white">Submitted contact</h1>
      <div class="row">
        <a class="center white" style="width: 100%;">You should recieve a response from me within 1-3 days</a>
      </div>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
    </div>
  </div>
  <script>
  //Only use screen size device begins with (since mobile browsers change screen size when scrolling down)
  $(".content")[0].style.top = ($(window).height() + 20) + "px";
  </script>
@endsection


@section("head")
  <script type="text/javascript" src="{{ asset('js/index.js') }}"></script>
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:700" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Quicksand" rel="stylesheet">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/brands.css" integrity="sha384-1KLgFVb/gHrlDGLFPgMbeedi6tQBLcWvyNUN+YKXbD7ZFbjX6BLpMDf0PJ32XJfX" crossorigin="anonymous">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/fontawesome.css" integrity="sha384-jLuaxTTBR42U2qJ/pm4JRouHkEDHkVqH0T1nyQXn1mZ7Snycpf6Rl25VBNthU4z0" crossorigin="anonymous">
@endsection

resources/views/home.blade.php
@extends('inc.app', ['title' => 'Marshall Ashdowne | Home'])

@section('content')
  <div class="title">
    <div class="container top-nav">
      <div class="row">
        <div class="col-12">
          <div class="logo" onclick="document.location = '/';"><object class="" data="{{ asset('/storage/images/Logo.svg') }}" type="image/svg+xml"></object></div>
          <a class="btn right" href="/contact">Contact Me</a>
        </div>
      </div>
    </div>
  </div>
  <br>
  <br>
  <div class="container">
    @if (session('status'))
        <div class="alert alert-success">
            {{ session('status') }}
        </div>
    @endif
    <div class="card contacts">
      <h1 class="center">Contacts</h1>
      <?php

      $contacts = \App\ContactForms::all();

      foreach ($contacts as $contact) {
        ?>

        <div class="row cursor grey-hover" onclick="document.location = '/contact/{{ $contact->id }}'">
          <div class="col">
            <a>{{ htmlspecialchars($contact->title) }}</a>
          </div>
        </div>
        <div class="divider"></div>

        <?php
      }

      ?>
    </div>
  </div>
@endsection

resources/views/inc/app.blade.php
<!doctype html>
<html lang="{{ app()->getLocale() }}">
    <head>
        <meta property="og:type"   content="article" />
        <meta property="og:url"    content="http://shitcoder.cf/"/>
        <meta property="og:title"  content="Marshall Ashdowne | Full Stack Developer" />
        <meta property="og:image"  content="{{ asset('/storage/images/Logo.png') }}" />
        <meta property="og:description"  content="I have a passion for building robust and stylish websites that started 3 years ago. Since then I have been starting and finishing websites to help online communitys, private individuals and open source projects" />
        <meta charset="utf-8">
        <meta name="csrf-token" content="{{csrf_token()}}">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="initial-scale=1">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" type="text/css" href="/css/app.css">
        <meta name="viewport" content="initial-scale=1">
        <div id='app'></div>
        <script src="/js/app.js"></script>
        <script src="/storage/js/index.js"></script>
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
        @yield('head')
        <title>{{$title}}</title>
        <link rel="shortcut icon" href="{{{ asset('storage/images/Logo.svg') }}}">
    </head>
    <body>
      @yield('content')

      @extends("inc.footer", ['contactMessage' => isset($contactMessage) ? $contactMessage : true ])
    </body>
</html>

resources/views/inc/footer.blade.php
<div class="footer">
  <div class="container">
    @if($contactMessage)
    <div class="row contact card">
      <a>Get in touch! Tell me about your website and <b>lets do this</b>.</a>
      <a href="/contact" class="btn">Contact Me</a>
    </div>
    @endif
    <div class="row footer-content">
        <div class="col-md-3 desktop-only">
          <h1 class="center white">Location</h1>
          <br>
          <a target="_blank" class="white" href="https://www.google.com/maps/@-43.5214422,170.8442749,7.25z">I currently live and study in the South Island of New Zealand!</a>
        </div>
        <div class="col-1 desktop-only"></div>
        <div class="col-md-4 footer-center">
          <br>
          <div class="row">
            <div class="col-2 col-md-offset-1">
              <a class="linkedin" target="_blank" href="https://www.linkedin.com/in/marshall-ashdowne-746989167/" title="Check out my LinkedIn"><span class="fab fa-linkedin-in"></span></a>
            </div>
            <div class="col-2">
              <a class="twitter" class="desktop-only" target="_blank" href="https://twitter.com/daarkzek" title="Send me a message on twitter"><span class="fab fa-twitter"></span></a>
            </div>
            <div class="col-2">
              <a class="gitlab" target="_blank" href="https://gitlab.com/darkzek" title="My Gitlab"><span class="fab fa-gitlab"></span></a>
            </div>
            <div class="col-2">
              <a class="reddit" class="desktop-only" target="_blank" href="https://reddit.com/u/monster4210" title="Upvote all my posts on reddit"><span class="fab fa-reddit-alien"></span></a>
            </div>
            <div class="col-2">
              <a class="email" target="_blank" href="mailto:daarkzek@protonmail.com" title="Send me an email"><span class="fas fa-envelope"></span></a>
            </div>
          </div>
        </div>
        <div class="col-1 desktop-only"></div>
        <div class="col-3 desktop-only">
          <h1 class="center white">Email</h1>
          <br>
          <a class="white" href="mailto:daarkzek@protonmail.com">Send me an email over at daarkzek@protonmail.com</a>
        </div>
    </div>
  </div>
</div>

resources/views/index.blade.php
@extends("inc.app", ['contactMessage', 'false'])

@section("content")
  <div class="title">
    <div class="container top-nav">
      <div class="row">
        <div class="col-12">
          <div class="logo" onclick="document.location = '/';"><object class="" data="{{ asset('/storage/images/Logo.svg') }}" type="image/svg+xml"></object></div>
          <a class="btn right" href="/contact">Contact Me</a>
        </div>
      </div>
    </div>
    <div class="container titles">
      <h1 class="white">Full Stack Developer</h1>
      <a class="white">I build beautiful user interfaces and server side software</a>
    </div>
  </div>
  <div class="content">
    <object class="devices" data="{{ asset('/storage/images/DevicesInkscapeEdited.svg') }}" type="image/svg+xml"></object>
    <div class="intro">
      <div class="container">
        <h1 class="white">Hi, I'm Marshall!</h1>
        <a class="white">I have a passion for building robust and stylish websites that started 3 years ago. Since then I have been starting and finishing websites to help online communities, private individuals and open source projects</a>
      </div>
    </div>
    <div class="container">
      <div class="talents card">
        <div class="row">
          <div class="col-md-4">
            <i class="material-icons">timeline</i>
            <h3>UI/UX Designer</h3><h5>Technologies Used</h5>
            <ul>
              <li><a>Inkscape</a></li>
              <li><a>Krita</a></li>
              <li><a>CSS</a></li>
              <li><a>Firefox</a></li>
            </ul>
            <a class="justify">The challenge of creating a functional but stylish website is what keeps me improving, always improving and adapting to new technology. The user experience is the most important part of making software because it alone can determine if a user uses or abandons the software.</a>
            
          </div>
          <div class="col-md-4 col-wall">
            <i class="material-icons">vertical_split</i>
            <h3>Front End Programming</h3>
            <h5>Technologies Used</h5>
            <ul>
              <li><a>Javascript</a></li>
              <li><a>HTML</a></li>
              <li><a>CSS</a></li>
              <li><a>Bootstrap</a></li>
              <li><a>Node.js</a></li>
            </ul>
            <a>I believe the front end is one of the more important parts of any website so it is very important to get right, keeping styling consistent to ensure your brand is instantly recognisable</a>
          </div>
          <div class="col-md-4 col-wall">
            <i class="material-icons">settings_system_daydream</i>
            <h3>API/Back End Developer</h3>
            <h5>Technologies Used</h5>
            <ul>
              <li><a>PHP/Composer</a></li>
              <li><a>Laravel</a></li>
              <li><a>Linux</a></li>
              <li><a>C#.NET</a></li>
              <li><a>Java</a></li>
              <li><a>Python</a></li>
            </ul>
            <a>I have learnt from many websites that the most important thing when developing back end software is to use a framework. My go to framework is <span class="cursor" onclick="var win = window.open('https://laravel.com/', '_blank');win.focus();" >Laravel</span> and <span class="cursor" onclick="var win = window.open('https://php.net/', '_blank');win.focus();" >PHP</span>, which allows you to make elegant REST API's for web applications and mobile applications alike.</a>
            <br class="desktop-only"><br class="desktop-only">
          </div>
        </div>
      </div>
    </div>
    <div class="container projects">
      <h1 class="center white">Personal Projects</h1>
      <br>
      <div class="row">
        <div class="col-md-4">
          <div class="card" style="background-image: url({{ asset("/storage/images/AshCollAutoLogin.png") }});" onclick="var win = window.open('https://gitlab.com/darkzek/AshcollAutoLogin', '_blank');win.focus();">
            <div class="display">
              <h3>AshcollAutoLogin</h3>
              <a>Is a android app to log users in to the school BYOD at Ashburton College</a>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="card" style="background-image: url({{ asset("/storage/images/Opinionated.png") }});" onclick="var win = window.open('https://opinionated.nz/', '_blank');win.focus();">
            <div class="display">
              <h3>Opinionated</h3>
              <a>Opinionated allows New Zealanders to share our opinions on the future of the country</a>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="card" style="background-image: url({{ asset("/storage/images/UDC.png") }});" onclick="var win = window.open('https://darkzek.github.io/UDC-Christmas-Event/Website/index.html', '_blank');win.focus();">
            <div class="display">
              <h3>UDC Christmas Event</h3>
              <a>Was an event which contained computer puzzles for users to solve</a>
            </div>
          </div>
        </div>
      </div>
    </div>
    <br>
    <br>
  <script>
  //Only use screen size device begins with (since mobile browsers change screen size when scrolling down)
  $(".content")[0].style.top = ($(window).height() + 20) + "px";
  </script>
@endsection


@section("head")
  <script type="text/javascript" src="{{ asset('js/index.js') }}"></script>
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:700" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Quicksand" rel="stylesheet">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/brands.css" integrity="sha384-1KLgFVb/gHrlDGLFPgMbeedi6tQBLcWvyNUN+YKXbD7ZFbjX6BLpMDf0PJ32XJfX" crossorigin="anonymous">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/fontawesome.css" integrity="sha384-jLuaxTTBR42U2qJ/pm4JRouHkEDHkVqH0T1nyQXn1mZ7Snycpf6Rl25VBNthU4z0" crossorigin="anonymous">
@endsection

resources/views/view-contact.blade.php
@extends("inc.app", ['contactMessage' => false])

@section("content")
  <div class="title">
    <div class="container top-nav">
      <div class="row">
        <div class="col-12">
          <div class="logo" onclick="document.location = '/';"><object class="" data="{{ asset('/storage/images/Logo.svg') }}" type="image/svg+xml"></object></div>
          <a class="btn right" href="/contact">Contact Me</a>
        </div>
      </div>
      <br>
      <form method="POST" action="{{ route('contact.destroy', ['id' => $form->id]) }}" class="form" >
        @method('DELETE')
        @csrf
        <h1 class="white">Contact #{{ $form->id }}</h1>
        <div class="divider"></div>
        <br>
        <label for="title">Title</label>
        <input type="text" class="form-control" id="title" disabled value="{{ $form->title }}" name="title">
        <br>
        <label for="content">Content</label>
        <textarea rows="10" name="content" disabled>{{ $form->content }}</textarea>
        <br>
        <br>
        <label for="contact">Contact Email</label>
        <input type="email" class="form-control" id="contact" name="contact" disabled value="{{ $form->contact }}">
        <br>
        <input class="btn form-control" type="submit" value="DELETE">
      </form>
    </div>
  </div>
  <script>
  //Only use screen size device begins with (since mobile browsers change screen size when scrolling down)
  $(".content")[0].style.top = ($(window).height() + 20) + "px";
  </script>
@endsection


@section("head")
  <script type="text/javascript" src="{{ asset('js/index.js') }}"></script>
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:700" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Quicksand" rel="stylesheet">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/brands.css" integrity="sha384-1KLgFVb/gHrlDGLFPgMbeedi6tQBLcWvyNUN+YKXbD7ZFbjX6BLpMDf0PJ32XJfX" crossorigin="anonymous">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/fontawesome.css" integrity="sha384-jLuaxTTBR42U2qJ/pm4JRouHkEDHkVqH0T1nyQXn1mZ7Snycpf6Rl25VBNthU4z0" crossorigin="anonymous">
@endsection